name: .NET

on: [ push, pull_request ]

env:
  DOTNET_SDK_VERSION: 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release -f net8.0 -o out/${{ github.event.repository.name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: out/${{ github.event.repository.name }}

  release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ github.event.repository.name }}
          path: out/${{ github.event.repository.name }}

      - name: Archive release
        uses: thedoctor0/zip-release@master
        with:
          directory: out
          path: ${{ github.event.repository.name }}
          type: 'zip'
          filename: 'generic.zip'
          exclusions: '*.json'

      - name: Create GitHub release
        id: github_release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "out/*"
          makeLatest: true
          release_name: ${{ github.event.repository.name }} V${{ github.ref_name }}
